---
- hosts: masters:slaves
  gather_facts: yes
  become: yes
  roles:
    - etc_config
    - container_features
    - dphys_swapfile
    - bootstrap_k3s

- hosts: masters
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s_master, tags: ['master'] }