---
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - etc_config
    - container_features
    - dphys_swapfile
    - bootstrap_k3s

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s_master, tags: ['master'] } 

# - hosts: slave
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: k3s_slave, tags: ['slave'] }