---
- name: Create backup copy of default configuration
  command: cp k3s.yaml k3s.yaml.backup1 
  args:
    chdir: /etc/rancher/k3s/
    creates: /etc/rancher/k3s/k3s.yaml.backup1 

- lineinfile:
    path: /etc/selinux/config
    regexp: '^localhost='
    line: 'server: https://{{inventory_hostname}}:6443'
    notify: k3s.service