---
- name: Create backup copy of default configuration
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /etc/rancher/k3s/k3s.yaml.backup  

- name: Replace localhost by server name 
  lineinfile:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: 'localhost'
    line: 'server: https://{{inventory_hostname}}:6443'
    mode: 0644
  notify: k3s.service