---
- name: Create backup copy of default configuration
  command: cp k3s.yaml k3s.yaml.backup
  args:
    chdir: /etc/rancher/k3s/
    creates: /etc/rancher/k3s/k3s.yaml.backup

- name: Replace localhost by server name 
  lineinfile:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: 'localhost'
    line: 'server: https://{{inventory_hostname}}:6443'
    mode: '666'
  notify: k3s.service