apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    service: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
   - port: 8080
     nodePort: 30801
     targetPort: 80