---
- name: Join node {{inventory_hostname}}({{ansible_host}}) to cluster 
  shell: >
    k3s agent --server https://k3s-master:6443 --cluster-secret {{cluster_secret}}

- name: Get joined slaves
  shell: >
    "k3s kubectl get node"
  register: node_list

- name: Check node list is complete
  shell: >
    echo "slave {{item}} is joined to cluster"
  with_items: "{{ groups['slaves']}}"
  when: node_list.stdout.find {{item}}



