---
- name: Create systemd service for agent
  template:
    src: k3s_agent.service.j2
    dest: /lib/systemd/system/k3s_agent.service
  notify: k3s_agent.service

- name: k3s agent service
  systemd:
    name: k3s_agent
    state: started
    enabled: yes