---
- name: Verify cgroup_enable is available
  shell: cat /boot/cmdline.txt | grep "cgroup_enable"
  register: cgroup_result

- name: See cgroup_enable result
  debug:
    msg: "See result {{ cgroup_result }}"