---
- name: Verify cpuset is enable
  shell: cat /boot/cmdline.txt | grep "cgroup_enable=cpuset"
  ignore_errors: yes
  register: cpuset_result

- name: Creating new cmdline with cpuset 
  shell: >
    echo "$(head -n1 /boot/cmdline.txt) cgroup_enable=cpuset"
  register: cmdline_cpuset
  when: cpuset_result.rc == 1 # meaning: the grep failed and there is no cgroup_enable 

- name: Adding cpuset to cmdline
  shell: "{{ cmdline_cpuset.stdout }} | tee /boot/cmdline.txt"


# - name: Verify memory is enable
#   shell: cat /boot/cmdline.txt | grep "cgroup_enable=memory"
#   ignore_errors: yes
#   register: memory_result

# - name: Add cgroup_enable 
#   shell: echo "cgroup_enable=memory" >> /boot/cmdline.txt
#   when: memory_result.rc == 1 # meaning: the grep failed and there is no cgroup_enable 